import Assets from './Assets';

export default {
	JavaScript: { logo: Assets.JavaScript, name: 'JavaScript' },
	TypeScript: { logo: Assets.TypeScript, name: 'TypeScript' },
	Java: { logo: Assets.Java, name: 'Java' },
	Python: { logo: Assets.Python, name: 'Python' },
	Csharp: { logo: Assets.Csharp, name: 'C#' },
	NodeJs: { logo: Assets.NodeJs, name: 'Node Js' },
	ReactJs: { logo: Assets.ReactJs, name: 'React Js' },
	Svelte: { logo: Assets.Svelte, name: 'Svelte' },
	Electron: { logo: Assets.Electron, name: 'Electron' },
	ExpressJs: { logo: Assets.ExpressJs, name: 'Express Js' },
	NestJs: { logo: Assets.NestJs, name: 'Nest Js' },
	Redis: { logo: Assets.Redis, name: 'Redis' },
	MongoDB: { logo: Assets.MongoDB, name: 'MongoDB' },
	Sass: { logo: Assets.Sass, name: 'Sass' },
	Tailwind: { logo: Assets.Tailwind, name: 'Tailwind' },
	CSS: { logo: Assets.CSS, name: 'CSS' },
	HTML: { logo: Assets.HTML, name: 'HTML' },
	AWS: { logo: Assets.AWS, name: 'AWS' },
	Bootstrap: { logo: Assets.Bootstrap, name: 'Bootstrap' },
	C: { logo: Assets.C, name: 'C' },
	Cpp: { logo: Assets.Cpp, name: 'C++' },
	Docker: { logo: Assets.Docker, name: 'Docker' },
	Go: { logo: Assets.Go, name: 'Go' },
	Nginx: { logo: Assets.Nginx, name: 'Nginx' },
	Pandas: { logo: Assets.Pandas, name: 'Pandas' },
	Rust: { logo: Assets.Rust, name: 'Rust', inverted: true },
};
